# STUDIO CONFIG
deadline:
  path:
    windows: "hello, I am the deadline windows path"
    linux: ~
    osx: ~
  default_pool: "hello, I am the deadline default pool"

python:
  path:
    windows: "C:/python27/python.exe"
    linux: "python"
    osx: "python"

email:
  name: CGTK
  from: "guoliangxu1987@163.com"
  password: "220558@wangyi"
  smtp_server: "smtp.163.com"
  port: 25
  ssl: yes

preset_paths:
  user_path:
    windows: "{env-USERPROFILE}/.cgtk"
    linux: "/usr/.cgtk"